### ISSUE TITLE
RKD query broken

### ISSUE THREAD

**Issue by ddeboer** [netwerk-digitaal-erfgoed/network-of-terms-catalog#107]
With #104, our RKD query has broken, suffering from https://github.com/comunica/comunica/issues/844:

`
Invalid SPARQL endpoint response from https://api.data.netwerkdigitaalerfgoed.nl/datasets/rkd/rkdartists/services/rkdartists/sparql (HTTP status 400):\nVirtuoso 37000 Error SP031: SPARQL compiler: The group does not contain triple pattern with '$label' object before bif:contains() predicate
`

I’ve tried to replace the `bif:contains` filter with a triple pattern:

```sparql
    ?label <bif:contains> (
        REPLACE(
            REPLACE("Gogh", "[.,]", " "),
            "(?<!AND)(?<!OR)[[:space:]]+(?!AND)(?!OR)(?!$)(?![[:space:]])",
            " AND ",
            "i"
        )
    ) 
```

but that gives:

```
Parse error on line 19:
...contains> (        REPLACE(
----------------------^
Expecting 'IRIREF', 'PNAME_NS', 'VAR', '(', 'INTEGER', 'NIL', '[', '<<', 'BLANK_NODE_LABEL', 'ANON', 'DECIMAL', 'DOUBLE', 'BOOLEAN', 'STRING_LITERAL1', 'STRING_LITERAL2', 'STRING_LITERAL_LONG1', 'STRING_LITERAL_LONG2', 'INTEGER_POSITIVE', 'DECIMAL_POSITIVE', 'DOUBLE_POSITIVE', 'INTEGER_NEGATIVE', 'DECIMAL_NEGATIVE', 'DOUBLE_NEGATIVE', 'PNAME_LN', got 'REPLACE'
```

First binding the replaced value and then using that, like this:

```sparql
BIND(REPLACE(…) as ?query)
?label <bif:contains> ?query
```

gives:

```
Virtuoso 22023 Error SR468: contains() can not be called as plain built-in function, it's a macro handled by SQL compiler
```

@sdevalk Any ideas about the right SPARQL/Virtuoso syntax here?

**Comment by EnnoMeijers** [comment]
This error is caused by the BIND statements in combination with the bif:contains. Virtuoso is rather picky about this. If you place the BIND before the bif:contains it throws this error. Although the BIND statements are after the bif:contains in the query my guess is that Comunica reorders the query lines and causes this problem. I disabled the BIND statements for now a did a fix on master tree (sorry for doing this directly).

**Comment by ddeboer** [comment]
Yep, that’s exactly the problem, as discussed in comunica/comunica#844. Thanks for reverting!

**Comment by sdevalk** [comment]
Great catch! The original Muziekschatten queries also suffered from the same problem. For the time being we use the rather limited solution, without our usual `REPLACE` expressions:

```sparql
label <bif:contains> ?query .
```

See https://github.com/netwerk-digitaal-erfgoed/network-of-terms-catalog/blob/master/catalog/queries/search/muziekschatten-personen.rq#L37-L38

However, I'd say that we shouldn't use this in the RKDartists query because we'd then loose search functionality. This means that the `?seeAlso` would have to wait until the Comunica issue is solved.

**Comment by EnnoMeijers** [comment]
I think we should examine the impact of moving away from `bif:contains` completely and just use the standard SPARQL CONTAINS. It might cost some extra response time but it would make our Virtuoso queries much more transparent and less error prone. And we wouldn't have to wait for the fix in Comunica which is open for sometime already and even has a bounty on it.

**Comment by ddeboer** [comment]
Will using native CONTAINS influence the quality of search results?

We can use `?label <bif:contains> ?query` in combination with #93, which has the additional upside of simplifying our queries.
