### ISSUE TITLE
Virtuoso: error when using a comma in search phrase

### ISSUE THREAD

**Issue by sdevalk** [netwerk-digitaal-erfgoed/network-of-terms-catalog#84]
The query underneath errors:

```graphql
query {
  terms(sources: ["https://data.netwerkdigitaalerfgoed.nl/rkd/rkdartists/sparql"],
        query: "Wagemans, Gerard") {
    source {
      name
    }
    result {
      __typename
      ... on Terms {
        terms {
          uri
          prefLabel
          altLabel
          scopeNote
        }
      }
      ... on Error {
        message
      }
    }
  }
}
```

Message: `Invalid SPARQL endpoint (https://api.data.netwerkdigitaalerfgoed.nl/datasets/rkd/rkdartists/services/rkdartists/sparql) response: undefined`

If I execute the [underlying SPARQL query](https://github.com/netwerk-digitaal-erfgoed/network-of-terms-catalog/blob/master/catalog/queries/search/rkdartists.rq) directly on endpoint `https://api.data.netwerkdigitaalerfgoed.nl/datasets/rkd/rkdartists/services/rkdartists/sparql`...

```sparql
PREFIX schema: <http://schema.org/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

CONSTRUCT {
    ?uri a skos:Concept ;
    skos:prefLabel ?schema_name ;
    skos:altLabel ?schema_alternateName ;
    skos:scopeNote ?schema_description .
}
WHERE {
    ?uri a ?type .
    VALUES ?type { schema:Person schema:Organization }
    ?uri ?name ?label .
    VALUES ?name { schema:name schema:alternateName }

    # Replace query "A B" with "A AND B", leaving queries "A AND B" or "A OR B" unchanged.
    FILTER (<bif:contains> (?label, REPLACE("Wagemans, Gerard", "(?<!AND)(?<!OR)[[:space:]]+(?!AND)(?!OR)", " AND ", "i")))

    OPTIONAL { ?uri schema:name ?schema_name . }
    OPTIONAL { ?uri schema:alternateName ?schema_alternateName . }
    OPTIONAL { ?uri schema:description ?schema_description . }
}
LIMIT 1000
```

...Virtuoso returns the message: `Virtuoso 37000 Error XM029: Free-text expression, line 1: syntax error at ,`

Apparently the comma in the search phrase `"Wagemans, Gerard"` isn't to Virtuoso's liking.

**Comment by EnnoMeijers** [comment]
It works when you add extra single quotes around the search string so <bif:contains> '"Wagenmans, Gerard"' works, but adding this to the REPLACE statement does not yet work for me.

**Comment by EnnoMeijers** [comment]
The problem is that the string "Wagemans, Gerard" is replaced by the regex magic into **"Wagemans, AND Gerard"**. I suggest to add [:punct:] to the magic in the following way: "(?<!AND)(?<!OR)[[:space:]**[:punct:]**]+(?!AND)(?!OR)". In this way the spaces and comma's are both treated as word separators. I will update the rkdartists.rq. If this works ok we should do this everywhere the same code is used.

**Comment by EnnoMeijers** [comment]
Actually [:punct:] is to broad and it will cause problems with "." in names, trying to find a working solution for something like: "Bandelier, Adolph F. A."

**Comment by EnnoMeijers** [comment]
I suggest to use the following line to filter the results:
`FILTER (<bif:contains> (?label, REPLACE(REPLACE(?query,"[[:punct:]]"," "),"(?<!AND)(?<!OR)[[:space:]]+(?!AND)(?!OR)(?!$)", " AND ", "i")  ))`

I added a replace statement to first replace any punctuation characters by single spaces. Then the regex magic is performed to combine the search words. For example **"Bandelier, Adolph F. A."** will be transformed in **"Bandelier AND Adolph AND F AND A"**. I added a check for end-of-string (?!$) because a space could be added to the end of the query string. Replacing the punctuation characters by single spaces is saver than replacing them by empty chars because this could clutter parts of the query string. 

@sdevalk @ddeboer any thoughts on this, my tests look promising but there could be pitfalls...

**Comment by EnnoMeijers** [comment]
Using the [:punct:] makes the replacement too greedy because it also filters the single quotes which are necessary for advanced searing for example searching with digits as in _Hofman '1939'_ or with wildcards _'Hofma*'_ so I narrowed down to only filtering comma's and dots in the following way: 

`FILTER (<bif:contains> (?label, REPLACE(REPLACE(?query,"[.,]"," "),"(?<!AND)(?<!OR)[[:space:]]+(?!AND)(?!OR)(?!$)", " AND ", "i")  ))`

**Comment by sdevalk** [comment]
With the release of https://github.com/netwerk-digitaal-erfgoed/network-of-terms-catalog/pull/94 this issue is solved. Closing.
